chore: check github token whitespaces, improve logrus format
sighupio/furyctl pull request #156
Opened 2023-01-11 13:55 UTC by luigibarbato

2023-01-11 14:30 UTC, omissis requested changes

2023-01-11 14:30 UTC, omissis commented on cmd/vendor.go
> +		if token := os.Getenv("GITHUB_TOKEN"); token != "" && strings.Contains(token, " ") {
`token != "" &&` seems redundant, as an empty string cannot contain a space

2023-01-11 14:30 UTC, omissis commented on cmd/vendor.go
> +			logrus.Warn("GITHUB_TOKEN seems to be malformed. Vendoring modules may fail. Please double check its content.\n")
```suggestion
			logrus.Warn("GITHUB_TOKEN contains a space character. As a result, vendoring modules may fail. If it's intended, you can ignore this warning.\n")
```

2023-01-13 11:23 UTC, ralgozino approved these changes
lgtm

2023-01-13 11:24 UTC, merged