feature/distro provider
sighupio/furyctl pull request #387
Opened 2023-06-01 11:45 UTC by alessiodionisi

SSIA

2023-06-01 14:03 UTC, nutellinoit requested changes
While testing we found two things:

1) We should check that at least a storageClass exists in the cluster with `kubectl get sc`
2) We should also thing as a general change to do the first apply with `kustomize build . | yq 'select(.kind == "CustomResourceDefinition")'`

2023-06-06 08:16 UTC, nutellinoit commented
When running this command: `./furyctl create cluster --distro-location /Users/samuelechiocca/github.com/sighupio/fury-distribution`

![Screenshot 2023-06-06 at 10 14 53](https://github.com/sighupio/furyctl/assets/25492971/55bee15a-4374-441b-8264-15c561f65d83)

to overcome this i needed `--skip-deps-validation`

2023-06-06 08:33 UTC, nutellinoit commented
We should also check if all the nodes in the cluster where we are installing the distro are `Ready`, otherwise it means that there is no CNI

2023-06-06 10:05 UTC, alessiodionisi commented
Pushed commits that fixes the validation error, checks storage class and node readiness.

2023-06-06 10:26 UTC, smerlos commented
---
Deploying KFDDistribution Cluster: Pre-conditions and Recommendations
---

## Pre-conditions for Deploying Cluster

Before deploying your cluster using `kind: KFDDistribution`, make sure to fulfill the following pre-conditions:

1. **All cluster nodes must be ready**: Ensure that each node in your Kubernetes cluster is in the 'Ready' state. Refer to the [Kubernetes node documentation](https://kubernetes.io/docs/concepts/architecture/nodes/) for additional guidance.
   
2. **A CNI (Container Network Interface) must be installed**: The cluster should be set up with a CNI that suits your use case. 

3. **A Storage Provider must be configured**: This involves setting up a `StorageClass` for your cluster. For more information, check out the [StorageClass documentation](https://kubernetes.io/docs/concepts/storage/storage-classes/).

## Recommendations

Here are some recommendations to optimize your KFDDistribution configuration:

- Consider configuring or removing `spec.distribution.common.[nodeSelector, tolerations]` based on your use case.

- Depending on your Kubernetes provider, be mindful of Gatekeeper policies. Add any namespaces necessary for the functioning of basic components (like the Storage Provider, CNI) or any other necessary namespaces, apart from `kube-system`, to the list of excluded namespaces (`spec.distribution.modules.policy.gatekeeper.additionalExcludedNamespaces`). Example: with Kind, you should add `local-path-storage` to the list of excluded namespaces.

Please feel free to modify and adapt these instructions based on your unique use case and technical requirements.

2023-06-13 08:20 UTC, alessiodionisi commented
⚠️ Merge after https://github.com/sighupio/fury-distribution/pull/95 and update `go.mod` dependency

2023-06-14 13:50 UTC, Al-Pragliola requested changes

2023-06-29 09:44 UTC, alessiodionisi commented
rebased

2023-06-29 10:58 UTC, omissis approved these changes

2023-06-29 10:58 UTC, omissis commented on internal/template/config.go
> +	if *tplSource.GetCustom() == nil {
this is a potential null pointer exception, chack for tplSource to be not nil
```suggestion
	if tplSource == nil || *tplSource.GetCustom() == nil {
```

2023-07-03 10:32 UTC, merged