feat: implement ephemeral delete
sighupio/furyctl pull request #455
Opened 2023-12-06 08:55 UTC by alessiodionisi

Closes #453.

2023-12-11 09:39 UTC, omissis commented on internal/apis/kfd/v1alpha2/distribution/delete/distribution.go
> +		if err != nil {
err gets overwritten, we should use two different names and embed it if needed

2023-12-11 09:39 UTC, omissis commented on internal/apis/kfd/v1alpha2/onpremises/delete/distribution.go
> +		if err != nil {
err variable gets overwritten

2023-12-11 09:43 UTC, Al-Pragliola requested changes

2024-01-11 11:16 UTC, omissis approved these changes

2024-01-11 11:16 UTC, merged