feat: add support for custom registry
sighupio/furyctl pull request #537
Opened 2024-09-04 15:39 UTC by alessiodionisi

Related to https://github.com/sighupio/fury-distribution/pull/257.

2024-09-10 08:43 UTC, ralgozino reviewed
The PR itself lgtm, I'm "requesting changes" until we address the open points in the linked PR.

Just to confirm, your idea is to backport the feature to the last releases with this PR and **not** to do a patch release of the distro?

2024-09-10 09:13 UTC, ralgozino commented
To answer myself, I just tried to create a cluster using KFD v1.29.3 and a build of furyctl from this branch and I get an error on the schema:

```bash
$ ~/src/github.com/sighupio/furyctl/furyctl apply cluster --phase kubernetes --config customRegistry.yaml
DEBU logging to: <REDACTED>/.furyctl/furyctl.1725959515-51887.log
DEBU Getting Home Directory Path...
INFO Downloading distribution...
INFO Compatibility patches applied for v1.29.3
INFO Validating configuration file...
ERRO error while validating configuration file: error while validating against schema: jsonschema: '/spec/kubernetes/advanced' does not validate with file:///var/folders/lb/zscvwt_s6fx6qdrfv4g51dsc0000gn/T/furyctl-2425192853/data/schemas/public/onpremises-kfd-v1alpha2.json#/properties/spec/$ref/properties/kubernetes/$ref/properties/advanced/$ref/additionalProperties: additionalProperties 'customRegistry' not allowed
```

2024-09-12 09:03 UTC, ralgozino requested changes
a per previous comments

2024-09-13 08:16 UTC, alessiodionisi commented
@ralgozino backports removed

2024-09-13 15:38 UTC, ralgozino submitted a review, later dismissed
changes related to the mirror feature lgtm.

BUT these changes are not enough for releasing, for example bumping the 1.28.x and 1.27.y max version is missing

2024-09-18 12:44 UTC, alessiodionisi commented
I think the PR is ready to release v0.29.7

2024-09-20 14:37 UTC, ralgozino requested changes

2024-09-20 14:37 UTC, ralgozino commented on docs/COMPATIBILITY_MATRIX.md
> +| 0.29.5        | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:
```suggestion
| 0.29.5        |                    | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          |
```

2024-09-20 14:37 UTC, ralgozino commented on docs/COMPATIBILITY_MATRIX.md
> +| 0.29.1        | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:
```suggestion
| 0.29.2        |                    | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          |
| 0.29.1        |                    | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          | :warning:          |
```

2024-09-20 14:37 UTC, ralgozino commented on go.mod
> +	github.com/sighupio/fury-distribution v1.29.4-rc.3
change this with the actual release once it's available

2024-09-20 14:38 UTC, ralgozino requested changes
The upgrade paths need to be added in `configs/upgrades`

2024-09-23 07:30 UTC, alessiodionisi commented
Added upgrade paths:
- 1.27.8 -> 1.27.9
- 1.28.3 -> 1.28.4
- 1.29.3 -> 1.29.4

minor upgrade paths:
- 1.27.9 -> 1.28.4
- 1.28.4 -> 1.29.4

2024-09-23 07:56 UTC, merged