fix: set clusterissuer route53 zone id by reading terraform outputs
sighupio/furyctl pull request #548
Opened 2024-10-14 13:56 UTC by alessiodionisi

## Changes

- Added missing `spec.distribution.modules.ingress.certManager.clusterIssuer.route53.hostedZoneId` on the EKS private schema by reading it from the Terraform outputs.
- Region is always eu-west-1 (is this ok?).

Closes #https://github.com/sighupio/fury-distribution/issues/134.

2024-10-17 13:23 UTC, ralgozino requested changes
Just a nit pick on the error handling. Besides that code-wise looks good, have you tested it?

2024-10-17 13:23 UTC, ralgozino commented on internal/apis/kfd/v1alpha2/ekscluster/common/distribution.go
> +			return nil, errTerraformOutputToStr
if we are returning this error only in this case, you should be more specific in the error text, saying that the Zone could not be found or something like that intead of error casting terraform output to string.

2024-10-18 07:17 UTC, alessiodionisi commented
> Just a nit pick on the error handling. Besides that code-wise looks good, have you tested it?

I have to test it, today I'll do that.

2024-10-21 16:56 UTC, alessiodionisi commented
Tested today, it works

2024-10-22 09:09 UTC, nutellinoit approved these changes
LGTM

2024-10-28 08:39 UTC, alessiodionisi commented
Re-requested the reviews due to change on error handling

2024-10-28 09:03 UTC, ralgozino approved these changes
lgtm 👍

2024-10-28 12:48 UTC, merged