[WIP] Add support for vSphere cluster
sighupio/furyctl pull request #55
Opened 2021-10-13 12:48 UTC by ralgozino

This PR adds support to the new feature of the vSphere provider that allows specifying a vSphere cluster (in the sense of the resource pools) instead of the nodes as target to create the Virtual Machines.

2022-03-07 10:02 UTC, lzecca78 approved these changes
LGTM

2022-03-08 14:16 UTC, nutellinoit requested changes

2022-03-08 14:16 UTC, nutellinoit commented on data/provisioners/cluster/vsphere/main.tf
> +  source = "https://github.com/sighupio/furyctl-provisioners/archive/refs/heads/support-for-vsphere-clusters.zip//furyctl-provisioners-support-for-vsphere-clusters/modules/cluster/vsphere"
Relase the provisioner and put the correct version here

2022-06-29 08:40 UTC, nutellinoit approved these changes
LGTM 🎉

2022-06-29 08:48 UTC, merged